# kubernetes/backstage.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backstage
  namespace: backstage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backstage
  template:
    metadata:
      labels:
        app: backstage
    spec:
      containers:
        - name: backstage
          image: backstagepp.azurecr.io/backstage:22
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 7007
#=====================================================================================================================              
#Adding the code we created manually
# apiVersion: apps/v1 #  for k8s versions before 1.9.0 use apps/v1beta2  and before 1.8.0 use extensions/v1beta1
# kind: Deployment
# metadata:
#   name: backstage
# spec:
#   selector:
#     matchLabels:
#       app: backstage
#   replicas: 3
#   template:
#     metadata:
#       labels:
#         app: backstage
#     spec:
#       containers:
#       - name: backstage
#         image: backstagepp.azurecr.io/backstage:8
#         resources:
#           requests:
#             cpu: 100m
#             memory: 100Mi
#         env:
#         - name: GET_HOSTS_FROM
#           value: dns
#           # If your cluster config does not include a dns service, then to
#           # instead access environment variables to find service host
#           # info, comment out the 'value: dns' line above, and uncomment the
#           # line below:
#           # value: env
#         ports:
#         - containerPort: 7007
